### ISSUE TITLE
QT5 port ?

### ISSUE THREAD

**Issue by Salamandar** [narunlifescience/AlphaPlot#11]
Just wanna know if you're gonna work on this :)
If you need some help please tell ! I don't know a lot about Qt but that has to change someday.

**Comment by narunlifescience** [comment]
Of corse Yes! QT5 port is definitely the highest priority right now. I am trying hard to drop QWT & QWTplot3D and replace it with QtCharts & QtDataVisualization(official QT libraries). These libraries are only available from Qt5.7. 
Helping hand is always a good thing and a must have for any open-source project. You are welcome to start working on any part of the project :)
please feel free to use Gitter for any development related discussions.

**Comment by Salamandar** [comment]
Hah, i did a huge job to support qwt6 ^^'' i only have some files left to compile. But if you change libs... Maybe I'll stop that and try to compile [qtw-old and Qt5]  ;)

**Comment by Salamandar** [comment]
Here is my fork : https://github.com/Salamandar/AlphaPlot
For now i commit --amend so it's not a good idea to pull ;)

**Comment by v2e** [comment]
@Salamandar 

> Hah, i did a huge job to support qwt6 ^^'' i only have some files left to compile. But if you change libs... Maybe I'll stop that and try to compile [qtw-old and Qt5] ;)

There is [an effort](https://github.com/highperformancecoder/scidavis/tree/qwt6-port) to port the related project SciDaVis to QWT6. Maybe, your code can be incorporated there? At least, judging by [this post](https://sourceforge.net/p/scidavis/scidavis-feature-requests/101/#1816), it looks like SciDaVis really needs some help on this.

**Comment by narunlifescience** [comment]
completed
