### ISSUE TITLE
Wrong (and random) values of errors on fit parameters - GSL 2.x issue

### ISSUE THREAD

**Issue by Fellypao** [narunlifescience/AlphaPlot#12]
This is a bug discovered in SciDAVis and I verified that it affects AlphaPlot too. The problem is related with the gsl 2.x library, since it doesn't happen when AlphaPlot/SciDAVis is buit using gsl 1.x.
For the complete description of the problem see ticket #290 of SciDAVis bugs page (https://sourceforge.net/p/scidavis/scidavis-bugs/290/)

**Comment by bbbear2002** [comment]
Mac version?

**Comment by narunlifescience** [comment]
Thanks, @Fellypao  for sharing the patch
