### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by apandada1** [narunlifescience/AlphaPlot#17]
When I run `make` (after `qmake`) I get the following error.
```
cd alphaplot/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/archisman/AlphaPlot/alphaplot/alphaplot.pro ) && make -f Makefile 
Project MESSAGE: Build configuration: Linux all dynamic
Project ERROR: Unknown module(s) in QT: datavisualization xmlpatterns
Makefile:51: recipe for target 'sub-alphaplot-make_first-ordered' failed
make: *** [sub-alphaplot-make_first-ordered] Error 3
```

I am using KDE Neon 5.19 (Ubuntu 18.04 base). I installed `zlibc` and `gsl-bin` packages.

**Comment by narunlifescience** [comment]
The error message shows two of the Qt5 modules used to build alphaplot is missing. please install qt5datavis3d and qt5xmlpatterns equivalent in ubuntu.

**Comment by apandada1** [comment]
It looks like [`=libqt5datavisualization5` ](https://packages.ubuntu.com/search?keywords=libqt5datavisualization5) is not available in Ubuntu 18.04 LTS (available 19.10 onwards). I will try manually installing its .deb package and let you know if that works. Meanwhile, it will be helpful if name of the packages of all the dependencies are mentioned in the Readme (not just the links to their website).

**Comment by apandada1** [comment]
The .deb package of `libqt5datavisualization5`, does not support 18.04 due to missing dependencies. Looks like I'll have to upgrade to 20.04. Anyway, please mention in readme the names of the packages for dependencies.

**Comment by narunlifescience** [comment]
if you have the patience, you can try to install a local version of qt5.14 or qt5.15 (Downloads for open source users) and build alphaplot using that. I should warn you that this process will take some time as the downloads will be around 10 to 20 gbs. but this will work!

**Comment by narunlifescience** [comment]
The issue is each Linux distro will have a different package name that is the reason I didn't mention it. please install libqt5datavisualization5 and libqt5xmlpatterns5 or libqt5datavisualization5-dev and libqt5xmlpatterns5-dev.

I will add the information to readme soon

**Comment by narunlifescience** [comment]
You can use this https://github.com/narunlifescience/AlphaPlot/issues/18 AppImage to run AlphaPlot. 
Note: the look and feel may not be ideal!

**Comment by apandada1** [comment]
The Appimage does not work in as it cannot find `GLIBC_2.29`, which is mentioned in #18 . I will soon install Linux Mint 20 once it is released (by the end of this month), and if the build works (it should, as all the dependencies will be available there), I'll close the issue. In the unlikely case that the build won't work, I will report back.

**Comment by narunlifescience** [comment]
Oh yes! I forgot about that :)

**Comment by filipestevao** [comment]
AlphaPlot is now available to install from Flathub:

https://flathub.org/apps/details/io.github.narunlifescience.AlphaPlot

If you use Linux Mint, just search for AlphaPlot in the software manager (mintinstall).

**Comment by filipestevao** [comment]
I'm not sure about that, but it looks like some libs are still missing.

A guess: `libglu1-mesa-dev`,`libqt5xmlpatterns5-dev`,`libqt5widgets5`

**Comment by apandada1** [comment]
`libqt5widgets5` and `libglu1-mesa-dev` were already installed. I installed `libqt5xmlpatterns5-dev` but the output does not change.

**Comment by apandada1** [comment]
I ran `make clean` and `make`, and this time it got built perfectly.
Last time I once ran `make -j4` to speed up the compilation, and that might be somehow responsible. I will try to isolate the reason why it did not compile, and soon close this GitHub issue.

**Comment by narunlifescience** [comment]
the following libraries are not required if you are using the master branch
`libqt5xmlpatterns5-dev, qml-module-qtdatavisualization, libmuparser-dev`
`libqt5xmlpatterns5-dev` was dropped as a dependency after v1.011.
`qml-module-qtdatavisualization` is not required.
`libmuparser-dev`the source code is already included. so this will be statically added to the executable.
