### ISSUE TITLE
Alphaplot packaged in AppImage format

### ISSUE THREAD

**Issue by filipestevao** [narunlifescience/AlphaPlot#18]
First, I would like to congratulate you for the AlphaPlot. I believe that this project has a promising future.

I don't know if you intend to package the application in other formats, but I packaged AlphaPlot in a AppImage:

[Repository](https://github.com/filipestevao/AlphaPlot-AppImage.git)

[Direct download](https://github.com/filipestevao/AlphaPlot-AppImage/releases/download/v1.011/AlphaPlot-1.011.glibc2.29-x86_64.AppImage)

I know that this is not the best way to package an AppImage and it is necessary to have `glibc` >= 2.29 (Ubuntu 18.04 has `glibc` = 2.27).

I believe that a flatpak format would be even better. However, I haven't been able to compile with flatpak-builder so far.

I hope that I have contributed in some way.

**Comment by narunlifescience** [comment]
Thanks a lot! packaging apps for all the Linux distros is an awful task at least for me :). I will add the download link to read me file.   
flatpak is better but atleast now people who strugle with building from source code can use this.
Thanks for the contribution.

**Comment by narunlifescience** [comment]
added download link to releases. do you mind if I upload the appimage to SourceForge ?

**Comment by filipestevao** [comment]
Of course not. Feel free to upload to SourceForge. I'm happy to help.

**Comment by narunlifescience** [comment]
done! :+1:

**Comment by filipestevao** [comment]
Good! :+1: 

Thank you for giving me credits in README
