### ISSUE TITLE
AlphaPlot in flatpak format

### ISSUE THREAD

**Issue by filipestevao** [narunlifescience/AlphaPlot#20]
Hello,
This issue is for registration purposes only.
As emailed to @narunlifescience, I successfully built AlphaPlot in flatpak format.

Here are the instructions for building:

1) Compile and install qtdatavis3d BaseApp:

```sh
git clone --branch=io.qt.qtdatavis3d.BaseApp https://github.com/filipestevao/flathub.git qtdatavis3d
cd qtdatavis3d
flatpak-builder --repo=qtdatavis3d --force-clean --install-deps-from=flathub build-dir io.qt.qtdatavis3d.BaseApp.yml
flatpak remote-add --user qtdatavis3d qtdatavis3d --no-gpg-verify
flatpak install --user qtdatavis3d io.qt.qtdatavis3d.BaseApp -y
```

2) Compile and install AlphaPlot app:

```sh
git clone --branch=io.github.narunlifescience.AlphaPlot https://github.com/filipestevao/flathub.git AlphaPlot
cd AlphaPlot
git clone https://github.com/flathub/shared-modules.git
flatpak-builder --repo=alphaplot --force-clean build-dir io.github.narunlifescience.AlphaPlot.yml
flatpak remote-add --user alphaplot alphaplot --no-gpg-verify
flatpak install --user alphaplot io.github.narunlifescience.AlphaPlot -y
```

I will make the pull request in the Flathub and keep informed here if everything goes well.

**Comment by narunlifescience** [comment]
:+1:

**Comment by filipestevao** [comment]
The maintainers of flathub suggested that [metainfo.xml](https://raw.githubusercontent.com/filipestevao/flathub/io.github.narunlifescience.AlphaPlot/io.github.narunlifescience.AlphaPlot.metainfo.xml) be added by upstream.

I'm not very good with examples, but one I know is the TeXstudio project in which [appdata is upstreamed](https://raw.githubusercontent.com/texstudio-org/texstudio/master/utilities/texstudio.appdata.xml).

Another question to think about (maybe in the future) is to add `\app` as a directory to install. I am currently using a patch to change the `\usr` to `\app`, as seen in [this diff](https://raw.githubusercontent.com/filipestevao/flathub/io.github.narunlifescience.AlphaPlot/patches/app-path.patch).

**Comment by narunlifescience** [comment]
upstreamed the metainfo to the master branch. Regarding the patch I will have a look at it later. If you have a neat way of solving it, please feel free to make a pull request. 
keep up the good work.

**Comment by filipestevao** [comment]
Thank you. I will study this issue of the directory `/app`.

Updated commands for compiling and installing the AlphaPlot  app:

```
git clone --branch=io.github.narunlifescience.AlphaPlot https://github.com/filipestevao/flathub.git AlphaPlot
cd AlphaPlot
git clone https://github.com/flathub/shared-modules.git
flatpak-builder --repo=alphaplot --force-clean --install-deps-from=flathub build-dir io.github.narunlifescience.AlphaPlot.yml
flatpak remote-add --user alphaplot alphaplot --no-gpg-verify
flatpak install --user alphaplot io.github.narunlifescience.AlphaPlot -y
```

**Comment by filipestevao** [comment]
Hello @narunlifescience,

AlphaPlot is now available on Flathub :tada: :clap:

https://flathub.org/apps/details/io.github.narunlifescience.AlphaPlot

I suggest inserting a [Flathub official badges](https://flathub.org/badges) in Readme. For example:

```html
<a href='https://flathub.org/apps/details/io.github.narunlifescience.AlphaPlot'><img width='240' alt='Download on Flathub' src='https://flathub.org/assets/badges/flathub-badge-en.png'/></a>
```

Now I will dedicate to maintaining the app on Flathub in the next releases and also help with improvements and bug fixes. I will no longer maintain the AppImage format.

**Comment by narunlifescience** [comment]
nice work!
added the badge to Readme. Feel free to make a pull request for improvements and bug fixes. I will close this issue then.

**Comment by filipestevao** [comment]
A test build of the latest AlphaPlot commits is available in Flathub Beta.

To install applications from the beta branch:

    flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

Search for `alphaplot` and choose flathub-beta:

    flatpak install alphaplot

If you install both the beta and the stable version of an app then they will be installed in parallel. However, only one will be showed in the menus. You can switch which one is currently showed like this [[ref.](https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/)]:

    flatpak make-current io.github.narunlifescience.AlphaPlot stable
    flatpak make-current io.github.narunlifescience.AlphaPlot beta

But from the command line you can always start any installed version explicitly, like this:

    flatpak run io.github.narunlifescience.AlphaPlot//stable
    flatpak run io.github.narunlifescience.AlphaPlot//beta

**Comment by narunlifescience** [comment]
:+1:
