### ISSUE TITLE
How to format text for labels?

### ISSUE THREAD

**Issue by aman-upadhyay** [narunlifescience/AlphaPlot#26]
I want to get options like super and subscripts for labels.

**Comment by narunlifescience** [comment]
you can directly paste unicode formatted text which contains subscripts or super scripts. 
here is an easy way
go to https://unicode-table.com/en/sets/superscript-and-subscript-letters/
select the unicode letter you want
![image](https://user-images.githubusercontent.com/11949260/112021818-af09c200-8b57-11eb-9e1c-8cd4fc4f324e.png)
select copy and then paste in the text box

**Comment by narunlifescience** [comment]
use <|> for line breaks

**Comment by aman-upadhyay** [comment]
Thanks for the tip.

**Comment by narunlifescience** [comment]
commit 4eb3b50c72e393aa6c9138f8349db5f5bd0ab692
