### ISSUE TITLE
Does not work on ubuntu 18 04

### ISSUE THREAD

**Issue by Nikita-Presnov** [narunlifescience/AlphaPlot#29]
Appimage out:
$ ./AlphaPlot-1.011-alpha-release-glibc2.29-x86_64.AppImage 
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by alphaplot)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libgsl.so.25)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Widgets.so.5)
alphaplot: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Widgets.so.5)
alphaplot: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Widgets.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5DataVisualization.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Gui.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5XmlPatterns.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Script.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Core.so.5)
alphaplot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Core.so.5)
alphaplot: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Core.so.5)
alphaplot: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libQt5Core.so.5)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libicui18n.so.67)
alphaplot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_AlphaPH0y3oX/usr/lib/libicuuc.so.67)

make out:
$ make
cd alphaplot/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /mnt/Disk_738/Downloads/AlphaPlot/alphaplot/alphaplot.pro ) && make -f Makefile 
Project MESSAGE: Build configuration: Linux all dynamic
Project ERROR: Unknown module(s) in QT: svg script scripttools datavisualization
Makefile:49: recipe for target 'sub-alphaplot-make_first-ordered' failed
make: *** [sub-alphaplot-make_first-ordered] Error 3

**The appimage stunt seems surprising to me, but on the whole I have such an impression that the authors of this program practically do not test it in a clean Linux virtual machine.**

**Comment by filipestevao** [comment]
Hi @Nikita-Presnov 

**AlphaPlot works perfectly if you install:**
- [Flatpak stable](https://flathub.org/apps/details/io.github.narunlifescience.AlphaPlot)
- [Flatpak beta](https://github.com/narunlifescience/AlphaPlot/issues/20#issuecomment-808984764)
- [Ubuntu ppa](https://github.com/narunlifescience/AlphaPlot#packagers)


**About AppImage:**
I did the packaging in AppImage and I am aware of this issue (see the discussions [here](https://github.com/narunlifescience/AlphaPlot/issues/18#issue-639917038) and [here](https://github.com/filipestevao/AlphaPlot-AppImage/issues/2)). For AppImage to work on all linux distributions, it is necessary to compile on older base systems and it was very difficult to get the necessary libraries for AlphaPlot.
That was one of the reasons that I archived the "AlphaPlot-AppImage" repository and I will not support it in next releases. I strongly recommend install the flatpak.

**To compile from source:**
See the discussion [here](https://github.com/narunlifescience/AlphaPlot/issues/17). You will need to download some libraries before runnig `qmake` or `make`.

**Comment by Nikita-Presnov** [comment]
You should write in README.md that AppImage version requires Ubuntu>=20.04 or another linux distributions that have glibc >= 2.29.
Also you should to write required libraries for compilation from source.
