### ISSUE TITLE
Flatpak application | Missing project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [narunlifescience/AlphaPlot#30]
Hello. As noticeable the worth mentioning mention regards to **project/organisation** name is missing and then dully reported as "_Unknown_" when exhibited by Flatseal '`flatpak run com.github.tchx84.Flatseal`'.

![Alphaplot](https://user-images.githubusercontent.com/26058215/117788248-e63f4a00-b24f-11eb-891b-f531a6217dd4.png)

**Comment by narunlifescience** [comment]
@filipestevao can you have a look at this please..

**Comment by Ricky-Tigg** [comment]
That so called _fix_ has no effect.

**Comment by filipestevao** [comment]
Yes, it was fixed. Run `flatpak update`

Flatseal:
![Captura de tela de 2021-05-12 06-19-02](https://user-images.githubusercontent.com/50991168/117951035-26530b00-b2ea-11eb-99d8-846c1bf5a89d.png)

Flathub site:
![Captura de tela de 2021-05-12 06-19-10](https://user-images.githubusercontent.com/50991168/117951062-2ce18280-b2ea-11eb-936b-625d685a7035.png)

**Comment by Ricky-Tigg** [comment]
` flatpak --system -y update` was implicit. Flathub had a delay to update its resources, since it your commit at last took effect since then.
