### ISSUE TITLE
alphaplot.desktop file should not be executable

### ISSUE THREAD

**Issue by drws** [narunlifescience/AlphaPlot#33]
Linux desktop files don't need to (shouldn't if you ask security guys) be set executable, which is a case with [alphaplot.desktop](https://github.com/narunlifescience/AlphaPlot/blob/master/data/alphaplot.desktop) file. The other desktop file in the repository [x-aproj.desktop](https://github.com/narunlifescience/AlphaPlot/blob/master/data/x-aproj.desktop) doesn't have this flaw.

**Comment by narunlifescience** [comment]
Thanks for reporting... will fix it soon
