### ISSUE TITLE
Proposal for mac retina-display resolution support

### ISSUE THREAD

**Issue by bbbear2002** [narunlifescience/AlphaPlot#4]
Could you consider to add mac retina-display resolution support into AlphaPlot, please? This would greatly enhance the user experience of AlphaPlot on Mac. Thank you @narunlifescience for your selfless contribution to this fantastic program.

**Comment by narunlifescience** [comment]
High DPI support is available in QT5.6 LT release.. but as of now Alphaplot can only use Qt4.. I will try to find an alternative to fix this problem..

**Comment by narunlifescience** [comment]
The text and buttons pixelation may get fixed if the following lines are added to Info.plist

    <key>NSHighResolutionCapable</key>
    <string>True</string>

check http://stackoverflow.com/questions/25494230/adding-support-for-retina-displays-hidpi-to-an-existing-qt4-application
could you check if that works & report back ?

**Comment by narunlifescience** [comment]
and give me a screenshot of new test build on a retina display...

**Comment by bbbear2002** [comment]
This release shows fine on retina display, please see: 
http://i4.piimg.com/ed04143f8592c3d0.png
http://i4.piimg.com/1ee1f08842d65279.png

**Comment by narunlifescience** [comment]
better retina display support will come with migration to qt 5.6 http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/ I will leave this open until then..

**Comment by narunlifescience** [comment]
check the new release and give me some screenshots. this issue should be fixed by now

**Comment by bbbear2002** [comment]
Can't open it on Catalina 10.15.4

Process:               alphaplot [7746]
Path:                  /Applications/alphaplot.app/Contents/MacOS/alphaplot
Identifier:            com.yourcompany.alphaplot
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           alphaplot [7746]
User ID:               501

Date/Time:             2020-05-08 00:15:22.881 +0800
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        FEBA910B-47E0-A32F-DDC8-F0307B0C2640

Sleep/Wake UUID:       E01E8727-0868-4044-BECE-D34B98F5D8D0

Time Awake Since Boot: 120000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
  Referenced from: /Applications/alphaplot.app/Contents/MacOS/alphaplot
  Reason: image not found

Binary Images:
       0x10ed97000 -        0x10f3b4ffb +com.yourcompany.alphaplot (0) <D7F9CA10-C529-3C9A-8690-E3B2FF07CE6F> /Applications/alphaplot.app/Contents/MacOS/alphaplot
       0x110030000 -        0x1100c1eff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld
    0x7fff2d76a000 -     0x7fff2d76effb  com.apple.agl (3.3.3 - AGL-3.3.3) <104E71F4-AC28-32C5-AA87-9D7DCA28BBC4> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff3ca35000 -     0x7fff3ca44ff7  com.apple.opengl (17.10.22 - 17.10.22) <4E9C4B23-6D44-3804-AFF8-84C3B060E8F5> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6b3af000 -     0x7fff6b3c1ff3  libz.1.dylib (76) <6A449C6A-DF88-36C1-8F2D-DB9A808263B5> /usr/lib/libz.1.dylib

Model: MacBookPro13,2, BootROM 265.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.9 GHz, 8 GB, SMC 2.37f21
Graphics: kHW_IntelIrisGraphics550Item, Intel Iris Graphics 550, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1600.4)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2

**Comment by narunlifescience** [comment]
please
[AlphaPlot.zip](https://github.com/narunlifescience/AlphaPlot/files/4595981/AlphaPlot.zip)
 test the application inside attached zip file and let me know

**Comment by bbbear2002** [comment]
This version is great

**Comment by narunlifescience** [comment]
can you share some screenshots.. If there is no display scaling issue, I will close this thread.
