### ISSUE TITLE
request: set column as label

### ISSUE THREAD

**Issue by yeKcim** [narunlifescience/AlphaPlot#5]
It could be really interesting to directly set a column as label :

![capture du 2016-09-18 22-30-18](https://cloud.githubusercontent.com/assets/10558744/18675189/ec916e64-7f51-11e6-9386-038a877e7583.png)

**Comment by narunlifescience** [comment]
This is also an issue related to other one dimensional data representations such as box and whisker plots as well. There are many ways to solve this one would be to make user select two columns one for data and other for column, another would be to choose the label column by right clicking the graph. usually one dimensional data  representations have limited labels which could be edited by hand; that is not an excuse though :). I will check which would be abetter solution without confusing users and keeping thinks simple. probably would fix in next release.
Thanks for reporting :)

**Comment by narunlifescience** [comment]
Fixed with commit https://github.com/narunlifescience/AlphaPlot/commit/34a17fbbb7567f08c8783682b87bea1dbac5b762
