### ISSUE TITLE
no difference between menu and direct icon

### ISSUE THREAD

**Issue by yeKcim** [narunlifescience/AlphaPlot#7]
in graph toolbar, lines icon is a menu, box plot is not, no display difference like a ▼ for menu (example)

**Comment by yeKcim** [comment]
It is possible to add the "menu information" directly in the icon file… ![example](https://cloud.githubusercontent.com/assets/10558744/18702067/44e4d784-7fe0-11e6-9c3d-d8beef88f0da.png) for example. No?

**Comment by narunlifescience** [comment]
I think this is a theming specific issue. there should be such an indicator shown by default but system themes can override them. could you please change system themes and check weather the indicator reappears...

**Comment by yeKcim** [comment]
- style OK : CDE, Cleanlooks, GTK+, Motif, Plastique, Windows
- style not OK : Oxygen

So it's only an oxygen bug, we can close
